name: build

on:
  push:
    branches: [ main ]
    paths:
      - 'initrd/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build initrd-magisk
      run: |
        cd initrd
        chmod -R 777 *; ln -fs /bin/ld-linux.so.2 lib/ld-linux.so.2; find * | cpio -o -H newc | gzip > ../initrd-magisk.img
        cd ..
    - uses: actions/upload-artifact@v1
      with:
        name: initrd-magisk
        path: initrd-magisk.img
